# Generated by Django 2.1.2 on 2018-10-15 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='commet',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg.Article'),
        ),
        migrations.AddField(
            model_name='commet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
