# Generated by Django 2.1.2 on 2018-10-15 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bg', '0002_auto_20181015_1622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commet',
            new_name='Comment',
        ),
    ]
