# Generated by Django 2.1.2 on 2018-10-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0003_auto_20181015_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
