# Generated by Django 2.1.2 on 2018-10-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0004_auto_20181015_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
