# Generated by Django 2.1.2 on 2018-10-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0005_auto_20181016_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
